import { describe, expect, it } from 'vitest';
import { renderVerifiedMarkdown } from '../../src/report/render-verified-markdown.js';
import { sampleControlledCredential } from '../fixtures/sample-readiness-report.js';
import {
  sampleExecutionRecordPath,
  sampleVerifiedReadinessReport,
} from '../fixtures/sample-verified-report.js';
import { sampleVerificationExecution } from '../fixtures/sample-verification-execution.js';
import { sampleVerificationPlan } from '../fixtures/sample-verification-plan.js';

describe('renderVerifiedMarkdown', () => {
  it('renders linkage, command timing, changed paths, exclusions, and the containment warning', async () => {
    const report = await sampleVerifiedReadinessReport();
    const markdown = renderVerifiedMarkdown(report);

    expect(markdown).toContain('## Local verification');
    expect(markdown).toContain(sampleVerificationPlan.planId);
    expect(markdown).toContain(sampleVerificationPlan.fingerprint);
    expect(markdown).toContain(sampleVerificationExecution.executionId);
    expect(markdown).toContain(sampleExecutionRecordPath);
    expect(markdown).toContain('package-script:build');
    expect(markdown).toContain('passed');
    expect(markdown).toContain('30000 ms');
    expect(markdown).toContain('coverage/index.html');
    expect(markdown).toContain('src/generated.ts');
    expect(markdown).toContain('package-script:lint');
    expect(markdown).toContain('excluded');
    expect(markdown).toContain('not a security sandbox');
  });

  it('ends with the exact disclaimer and never adds secrets, a score, verdict, emoji, or authorship', async () => {
    const report = await sampleVerifiedReadinessReport();
    const markdown = renderVerifiedMarkdown(report);
    const prohibited = [
      'readiness score',
      'overall score',
      'certified production ready',
      'launch verdict',
      'generated by ai',
      'authored by ai',
      '✅',
      '❌',
    ];

    expect(markdown.endsWith(`${report.disclaimer}\n`)).toBe(true);
    expect(markdown).not.toContain(sampleControlledCredential);
    for (const text of prohibited) expect(markdown.toLowerCase()).not.toContain(text);
  });
});
