import { describe, expect, it } from 'vitest';
import { renderVerifiedMarkdown } from '../../src/report/render-verified-markdown.js';
import { sampleControlledCredential } from '../fixtures/sample-readiness-report.js';
import {
  sampleExecutionRecordPath,
  sampleVerifiedReadinessReport,
} from '../fixtures/sample-verified-report.js';
import { sampleVerificationExecution } from '../fixtures/sample-verification-execution.js';
import { sampleVerificationPlan } from '../fixtures/sample-verification-plan.js';
import { VERIFICATION_DISCLAIMER } from '../../src/verification/contract-constants.js';

describe('renderVerifiedMarkdown', () => {
  it('renders linkage, command timing, changed paths, exclusions, and the containment warning', async () => {
    const report = await sampleVerifiedReadinessReport();
    const markdown = renderVerifiedMarkdown(report);

    expect(markdown).toContain('## Local verification');
    expect(markdown).toContain(sampleVerificationPlan.planId);
    expect(markdown).toContain(sampleVerificationPlan.fingerprint);
    expect(markdown).toContain(sampleVerificationExecution.executionId);
    expect(markdown).toContain(sampleExecutionRecordPath);
    expect(markdown).toContain('package-script:build');
    expect(markdown).toContain('passed');
    expect(markdown).toContain('30000 ms');
    expect(markdown).toContain('coverage/index.html');
    expect(markdown).toContain('src/generated.ts');
    expect(markdown).toContain('package-script:lint');
    expect(markdown).toContain('excluded');
    expect(markdown).toContain('not a security sandbox');
    expect(markdown).toContain('### Observation boundary');
    expect(markdown).toContain('project-observation/0.1');
    expect(markdown).toContain('Excluded directories:');
    for (const directory of ['.git', '.postvibe', 'coverage', 'dist', 'node_modules']) {
      expect(markdown).toContain(`\` ${directory} \``);
    }
    expect(markdown).toContain('/example/project/.postvibe/execution.json');
    expect(markdown).toContain('Symlinks and non-regular files are not observed');
    expect(markdown).toContain('Inaccessible paths fail observation');
    expect(markdown).toContain('Only content SHA-256 metadata is recorded');
  });

  it('renders the approved command boundary and ends with the exact disclaimer', async () => {
    const report = await sampleVerifiedReadinessReport();
    const markdown = renderVerifiedMarkdown(report);

    expect(markdown).toContain('## Command approval boundary');
    expect(markdown).toContain('The exact command declaration and direct launch details were checked before start.');
    expect(markdown).toContain('This does not freeze imported files, dependencies, operating-system code, or changes made by other processes.');
    expect(markdown).toContain([
      '## Command approval boundary',
      '',
      'The exact command declaration and direct launch details were checked before start.',
      '',
      'This does not freeze imported files, dependencies, operating-system code, or changes made by other processes.',
      '',
      '### Containment warning',
    ].join('\n'));
    expect(markdown.endsWith(`${VERIFICATION_DISCLAIMER}\n`)).toBe(true);
  });

  it('rejects a report whose command approval boundary is not the exact validated policy', async () => {
    const report = await sampleVerifiedReadinessReport();
    report.verification.approvalBoundary.policyVersion = 'command-authorization/untrusted' as never;

    expect(() => renderVerifiedMarkdown(report)).toThrow('Cannot render an unvalidated command approval boundary.');
  });

  it('never adds secrets, a score, verdict, emoji, or authorship', async () => {
    const report = await sampleVerifiedReadinessReport();
    const markdown = renderVerifiedMarkdown(report);
    const prohibited = [
      'readiness score',
      'overall score',
      'certified production ready',
      'launch verdict',
      'generated by ai',
      'authored by ai',
      '✅',
      '❌',
    ];

    expect(markdown).not.toContain(sampleControlledCredential);
    for (const text of prohibited) expect(markdown.toLowerCase()).not.toContain(text);
  });

  it('renders every project-controlled verification field as safe single-line code', async () => {
    const report = await sampleVerifiedReadinessReport();
    report.verification.executionRecordPath = 'records/report`tick`\n## record-injection';
    const verificationFindings = report.findings.filter(
      ({ checkId }) => checkId === 'universal-verification.commands',
    );
    const commandEvidence = verificationFindings
      .flatMap(({ evidence }) => evidence)
      .find(({ kind }) => kind === 'command');
    const changedPathEvidence = verificationFindings
      .flatMap(({ evidence }) => evidence)
      .find(({ kind }) => kind === 'file');
    const boundaryFinding = verificationFindings.find(({ unverifiedBoundaries }) => unverifiedBoundaries);
    if (!commandEvidence || !changedPathEvidence || !boundaryFinding) throw new Error('expected verification evidence');
    commandEvidence.location = 'package.json`source`\n## source-injection';
    changedPathEvidence.location = 'dist/changed`path`\n## path-injection';
    boundaryFinding.unverifiedBoundaries = ['excluded`reason`\n## boundary-injection\u0007'];

    const markdown = renderVerifiedMarkdown(report);

    for (const heading of [
      'record-injection',
      'source-injection',
      'path-injection',
      'boundary-injection',
    ]) {
      expect(markdown).not.toMatch(new RegExp(`^## ${heading}$`, 'm'));
      expect(markdown).toContain(`\\n## ${heading}`);
    }
    expect(markdown).toContain('`tick`');
    expect(markdown).toContain('`source`');
    expect(markdown).toContain('`path`');
    expect(markdown).toContain('`reason`');
    expect(markdown).toContain('\\u0007');
  });

  it('makes Unicode line separators and C1 controls visible instead of structural', async () => {
    const report = await sampleVerifiedReadinessReport();
    report.verification.executionRecordPath = 'records/report\u2028## unicode-injection\u0085tail';

    const markdown = renderVerifiedMarkdown(report);

    expect(markdown).not.toMatch(/^## unicode-injection/mu);
    expect(markdown).toContain('\\u2028## unicode-injection\\u0085tail');
  });

  it('safely renders every inherited project-controlled field and makes bidi controls visible', async () => {
    const report = await sampleVerifiedReadinessReport();
    const preservedFinding = report.findings.find(({ id }) => id === 'secret-exposure.fixture-secret');
    const unverifiedFinding = report.findings.find(({ id }) => id === 'launch-essentials.privacy-unverified');
    const preservedExecution = report.checkExecutions.find(({ checkId }) => checkId === 'secret-exposure.scan');
    const checkGap = report.coverageGaps.find(({ checkId }) => checkId === 'launch-essentials.privacy-notice');
    const domainGap = report.coverageGaps.find(({ checkId }) => checkId === undefined);
    const artifact = report.manifest.artifacts[0];
    if (!preservedFinding || !unverifiedFinding || !preservedExecution || !checkGap || !domainGap || !artifact) {
      throw new Error('expected preserved Level 0 report content');
    }

    const bidiAndFormattingControls = '\u00ad\u061c\u180e\u200b\u200c\u200d\u200e\u200f\u202a\u202b\u202c\u202d\u202e\u2060\u2061\u2062\u2063\u2064\u2066\u2067\u2068\u2069\u206a\u206b\u206c\u206d\u206e\u206f\ufeff';
    const headings: string[] = [];
    const adversarial = (label: string): string => {
      headings.push(label);
      return `ordinary/${label}\`tick\`${bidiAndFormattingControls}\n## ${label}-injection`;
    };

    report.manifest.projectRoot = adversarial('project-root');
    artifact.value = adversarial('artifact-value') as typeof artifact.value;
    preservedFinding.title = adversarial('finding-title');
    preservedFinding.checkId = adversarial('finding-check-id');
    preservedFinding.checkVersion = adversarial('finding-check-version');
    preservedFinding.skillVersion = adversarial('finding-skill-version');
    preservedFinding.outcome = adversarial('finding-outcome') as typeof preservedFinding.outcome;
    preservedFinding.impact = adversarial('finding-impact');
    preservedFinding.recommendation = adversarial('finding-recommendation');
    preservedFinding.verification = adversarial('finding-verification');
    const preservedEvidence = preservedFinding.evidence[0];
    if (!preservedEvidence) throw new Error('expected preserved finding evidence');
    preservedEvidence.location = adversarial('finding-evidence-location');
    unverifiedFinding.title = adversarial('unverified-title');
    unverifiedFinding.unverifiedBoundaries = [adversarial('unverified-boundary')];
    preservedExecution.checkId = adversarial('execution-check-id');
    preservedExecution.checkVersion = adversarial('execution-check-version');
    preservedExecution.skillId = adversarial('execution-skill-id');
    preservedExecution.skillVersion = adversarial('execution-skill-version');
    preservedExecution.status = adversarial('execution-status') as typeof preservedExecution.status;
    preservedExecution.domains = [
      adversarial('execution-domain') as typeof preservedExecution.domains[number],
    ];
    checkGap.checkId = adversarial('check-gap-id');
    checkGap.status = adversarial('check-gap-status') as typeof checkGap.status;
    checkGap.reason = adversarial('check-gap-reason');
    domainGap.domains = [adversarial('domain-gap-domain') as typeof domainGap.domains[number]];
    domainGap.reason = adversarial('domain-gap-reason');

    const markdown = renderVerifiedMarkdown(report);

    for (const heading of headings) {
      expect(markdown).not.toMatch(new RegExp(`^## ${heading}-injection$`, 'mu'));
      expect(markdown).toContain(`\\n## ${heading}-injection`);
    }
    expect(markdown).not.toMatch(/[\u00ad\u061c\u180e\u200b-\u200f\u202a-\u202e\u2060-\u206f\ufeff]/u);
    for (const escaped of ['\\u061c', '\\u200e', '\\u200f', '\\u202a', '\\u202e', '\\u2066', '\\u2069']) {
      expect(markdown).toContain(escaped);
    }
    expect(markdown).toContain('ordinary/artifact-value');
    expect(markdown).toContain('coverage/index.html');
    expect(markdown.endsWith(`${report.disclaimer}\n`)).toBe(true);
  });
});
