import { describe, expect, it } from 'vitest';
import { renderVerifiedMarkdown } from '../../src/report/render-verified-markdown.js';
import { sampleControlledCredential } from '../fixtures/sample-readiness-report.js';
import {
  sampleExecutionRecordPath,
  sampleVerifiedReadinessReport,
} from '../fixtures/sample-verified-report.js';
import { sampleVerificationExecution } from '../fixtures/sample-verification-execution.js';
import { sampleVerificationPlan } from '../fixtures/sample-verification-plan.js';

describe('renderVerifiedMarkdown', () => {
  it('renders linkage, command timing, changed paths, exclusions, and the containment warning', async () => {
    const report = await sampleVerifiedReadinessReport();
    const markdown = renderVerifiedMarkdown(report);

    expect(markdown).toContain('## Local verification');
    expect(markdown).toContain(sampleVerificationPlan.planId);
    expect(markdown).toContain(sampleVerificationPlan.fingerprint);
    expect(markdown).toContain(sampleVerificationExecution.executionId);
    expect(markdown).toContain(sampleExecutionRecordPath);
    expect(markdown).toContain('package-script:build');
    expect(markdown).toContain('passed');
    expect(markdown).toContain('30000 ms');
    expect(markdown).toContain('coverage/index.html');
    expect(markdown).toContain('src/generated.ts');
    expect(markdown).toContain('package-script:lint');
    expect(markdown).toContain('excluded');
    expect(markdown).toContain('not a security sandbox');
  });

  it('ends with the exact disclaimer and never adds secrets, a score, verdict, emoji, or authorship', async () => {
    const report = await sampleVerifiedReadinessReport();
    const markdown = renderVerifiedMarkdown(report);
    const prohibited = [
      'readiness score',
      'overall score',
      'certified production ready',
      'launch verdict',
      'generated by ai',
      'authored by ai',
      '✅',
      '❌',
    ];

    expect(markdown.endsWith(`${report.disclaimer}\n`)).toBe(true);
    expect(markdown).not.toContain(sampleControlledCredential);
    for (const text of prohibited) expect(markdown.toLowerCase()).not.toContain(text);
  });

  it('renders every project-controlled verification field as safe single-line code', async () => {
    const report = await sampleVerifiedReadinessReport();
    report.verification.executionRecordPath = 'records/report`tick`\n## record-injection';
    const verificationFindings = report.findings.filter(
      ({ checkId }) => checkId === 'universal-verification.commands',
    );
    const commandEvidence = verificationFindings
      .flatMap(({ evidence }) => evidence)
      .find(({ kind }) => kind === 'command');
    const changedPathEvidence = verificationFindings
      .flatMap(({ evidence }) => evidence)
      .find(({ kind }) => kind === 'file');
    const boundaryFinding = verificationFindings.find(({ unverifiedBoundaries }) => unverifiedBoundaries);
    if (!commandEvidence || !changedPathEvidence || !boundaryFinding) throw new Error('expected verification evidence');
    commandEvidence.location = 'package.json`source`\n## source-injection';
    changedPathEvidence.location = 'dist/changed`path`\n## path-injection';
    boundaryFinding.unverifiedBoundaries = ['excluded`reason`\n## boundary-injection\u0007'];

    const markdown = renderVerifiedMarkdown(report);

    for (const heading of [
      'record-injection',
      'source-injection',
      'path-injection',
      'boundary-injection',
    ]) {
      expect(markdown).not.toMatch(new RegExp(`^## ${heading}$`, 'm'));
      expect(markdown).toContain(`\\n## ${heading}`);
    }
    expect(markdown).toContain('`tick`');
    expect(markdown).toContain('`source`');
    expect(markdown).toContain('`path`');
    expect(markdown).toContain('`reason`');
    expect(markdown).toContain('\\u0007');
  });

  it('makes Unicode line separators and C1 controls visible instead of structural', async () => {
    const report = await sampleVerifiedReadinessReport();
    report.verification.executionRecordPath = 'records/report\u2028## unicode-injection\u0085tail';

    const markdown = renderVerifiedMarkdown(report);

    expect(markdown).not.toMatch(/^## unicode-injection/mu);
    expect(markdown).toContain('\\u2028## unicode-injection\\u0085tail');
  });
});
